/* GTEL — languagecat.js : dictionnaire de traduction (FR/AR/EN) */
window.GTEL_I18N = {
  "fr": {
    "nav.home": "Accueil",
    "nav.solutions": "Solutions",
    "nav.catalogue": "Catalogue",
    "nav.about": "À Propos",
    "nav.contact": "Nous Contacter",
    "solutions.infra_digitale": "Infrastructure Digitale",
    "solutions.infra_reseau": "Infrastructure Réseau",
    "solutions.datacenter": "Datacenter",
    "solutions.cybersecurite": "Cybersécurité",
    "solutions.videosurveillance": "Vidéosurveillance",
    "solutions.controle_acces": "Contrôle d'Accès",
    "solutions.telephonie_ip": "Téléphonie IP",
    "solutions.salles_reunion": "Salles de Réunion",
    "solutions.sonorisation": "Sonorisation",
    "solutions.managed": "Services Managés",
    "hero.badge": "GTEL Store — Matériel Professionnel",
    "hero.title.pre": "Catalogue de",
    "hero.title.accent": "Technologies B2B",
    "hero.desc": "Sélection rigoureuse des meilleurs équipements réseaux, serveurs d'entreprise, sécurité active et solutions de collaboration. Configuré et déployé sur tout le Maroc.",
    "hero.metric1.value": "16+",
    "hero.metric1.label": "Références en stock",
    "hero.metric2.value": "4",
    "hero.metric2.label": "Familles d'équipements",
    "hero.metric3.value": "100%",
    "hero.metric3.label": "Support B2B Maroc",
    "filters.all": "Tous",
    "filters.network": "Réseaux &amp; Sécurité",
    "filters.server": "Serveurs &amp; Stockage",
    "filters.comms": "Collaboration &amp; VoIP",
    "filters.cctv": "Contrôle d'Accès &amp; CCTV",
    "search.placeholder": "Rechercher par modèle, marque…",
    "results.count": "{n} équipements",
    "empty.title": "Aucun équipement trouvé",
    "empty.desc": "Désolé, aucun matériel ne correspond à vos critères de recherche. Essayez d'autres mots clés.",
    "cta.requestPrice": "Demander Prix",
    "price.label": "Tarif B2B",
    "ctaband.title": "Un projet d'équipement à chiffrer ? Nos consultants IT répondent en 24h.",
    "ctaband.button": "Demander une étude",
    "footer.brandDesc": "Expert marocain en solutions réseaux, cyber-intelligence et infrastructures de télécommunications intégrées à Casablanca et sur tout le royaume.",
    "footer.navTitle": "Navigation",
    "footer.navHome": "Accueil",
    "footer.navSolutions": "Nos Solutions",
    "footer.navCatalogue": "Catalogue Équipements",
    "footer.navAbout": "Notre Expertise",
    "footer.officeTitle": "Bureau Maroc",
    "footer.address": "Angle Rue Al-Quaid / Bd d'Anfa, Casablanca, Maroc",
    "footer.phone": "+212 (0) 522 45 67 89 / 90",
    "footer.email": "contact@gtel.ma",
    "footer.copy": "© 2025 GTEL. Tous droits réservés. Intégré avec expertise au Maroc.",
    "footer.legal": "Mentions Légales",
    "footer.privacy": "Politique de Confidentialité",
    "modal.title": "Demande d'Étude B2B",
    "modal.desc": "Configurez vos raccordements d'équipement avec la rigueur de consultants IT certifiés.",
    "modal.titleProduct": "Demande de Cotation B2B",
    "modal.labelName": "Nom complet / Entreprise *",
    "modal.placeholderName": "Ex: Auto Hall Maroc",
    "modal.labelEmail": "Adresse e-mail professionnelle *",
    "modal.placeholderEmail": "Ex: achat@societe.ma",
    "modal.labelPhone": "Numéro de téléphone *",
    "modal.placeholderPhone": "Ex: +212 661 234 567",
    "modal.labelProduct": "Matériel d'intérêt",
    "modal.labelQty": "Quantité Estimée",
    "modal.submit": "Envoyer ma demande de tarif",
    "modal.requiredAlert": "Veuillez remplir les champs obligatoires (*)",
    "toast.success.title": "Demande Envoyée avec Succès !",
    "toast.success.desc": "Nos analystes réseau préparent votre cotation personnalisée.",
    "toast.local.desc": "Demande envoyée (Mode Local/Simulation) !",
    "theme.toLight": "Passer au mode clair",
    "theme.toDark": "Passer au mode sombre",
    "lang.current": "FR"
  },
  "ar": {
    "nav.home": "الرئيسية",
    "nav.solutions": "الحلول",
    "nav.catalogue": "الكتالوج",
    "nav.about": "من نحن",
    "nav.contact": "اتصل بنا",
    "solutions.infra_digitale": "البنية التحتية الرقمية",
    "solutions.infra_reseau": "البنية التحتية للشبكات",
    "solutions.datacenter": "مركز البيانات",
    "solutions.cybersecurite": "الأمن السيبراني",
    "solutions.videosurveillance": "المراقبة بالفيديو",
    "solutions.controle_acces": "التحكم في الدخول",
    "solutions.telephonie_ip": "الهاتف عبر بروتوكول IP",
    "solutions.salles_reunion": "قاعات الاجتماعات",
    "solutions.sonorisation": "الصوتيات",
    "solutions.managed": "الخدمات المُدارة",
    "hero.badge": "متجر GTEL — معدات احترافية",
    "hero.title.pre": "كتالوج",
    "hero.title.accent": "التقنيات B2B",
    "hero.desc": "انتقاء دقيق لأفضل معدات الشبكات وخوادم المؤسسات والأمن النشط وحلول التعاون. تركيب ونشر في جميع أنحاء المغرب.",
    "hero.metric1.value": "+16",
    "hero.metric1.label": "مرجع متوفر",
    "hero.metric2.value": "4",
    "hero.metric2.label": "فئات المعدات",
    "hero.metric3.value": "100%",
    "hero.metric3.label": "دعم للشركات بالمغرب",
    "filters.all": "الكل",
    "filters.network": "الشبكات والأمن",
    "filters.server": "الخوادم والتخزين",
    "filters.comms": "التعاون و VoIP",
    "filters.cctv": "التحكم في الدخول والمراقبة",
    "search.placeholder": "ابحث حسب الموديل أو العلامة…",
    "results.count": "{n} معدات",
    "empty.title": "لم يتم العثور على أي معدات",
    "empty.desc": "عذرًا، لا يوجد معدات تطابق معايير بحثك. جرّب كلمات مفتاحية أخرى.",
    "cta.requestPrice": "اطلب السعر",
    "price.label": "سعر الشركات",
    "ctaband.title": "لديك مشروع تجهيز تريد تسعيره؟ يرد مستشارونا التقنيون خلال 24 ساعة.",
    "ctaband.button": "اطلب دراسة",
    "footer.brandDesc": "خبير مغربي في حلول الشبكات والاستخبارات السيبرانية والبنى التحتية للاتصالات المتكاملة في الدار البيضاء وجميع أنحاء المملكة.",
    "footer.navTitle": "التنقل",
    "footer.navHome": "الرئيسية",
    "footer.navSolutions": "حلولنا",
    "footer.navCatalogue": "كتالوج المعدات",
    "footer.navAbout": "خبرتنا",
    "footer.officeTitle": "المكتب بالمغرب",
    "footer.address": "زاوية شارع القائد / شارع أنفا، الدار البيضاء، المغرب",
    "footer.phone": "212 (0) 522 45 67 89 / 90+",
    "footer.email": "contact@gtel.ma",
    "footer.copy": "© 2025 GTEL. جميع الحقوق محفوظة. أُنجز بخبرة في المغرب.",
    "footer.legal": "الإشعارات القانونية",
    "footer.privacy": "سياسة الخصوصية",
    "modal.title": "طلب دراسة للشركات",
    "modal.desc": "قم بتهيئة توصيلات معداتك بدقة مستشارين معتمدين في تكنولوجيا المعلومات.",
    "modal.titleProduct": "طلب عرض سعر للشركات",
    "modal.labelName": "الاسم الكامل / الشركة *",
    "modal.placeholderName": "مثال: Auto Hall Maroc",
    "modal.labelEmail": "البريد الإلكتروني المهني *",
    "modal.placeholderEmail": "مثال: achat@societe.ma",
    "modal.labelPhone": "رقم الهاتف *",
    "modal.placeholderPhone": "مثال: 212 661 234 567+",
    "modal.labelProduct": "المعدات المطلوبة",
    "modal.labelQty": "الكمية التقديرية",
    "modal.submit": "إرسال طلب السعر",
    "modal.requiredAlert": "يرجى ملء الحقول الإلزامية (*)",
    "toast.success.title": "تم إرسال الطلب بنجاح!",
    "toast.success.desc": "يقوم محللو الشبكة لدينا بإعداد عرض السعر الخاص بك.",
    "toast.local.desc": "تم إرسال الطلب (وضع محلي/تجريبي)!",
    "theme.toLight": "التبديل إلى الوضع الفاتح",
    "theme.toDark": "التبديل إلى الوضع الداكن",
    "lang.current": "AR"
  },
  "en": {
    "nav.home": "Home",
    "nav.solutions": "Solutions",
    "nav.catalogue": "Catalogue",
    "nav.about": "About",
    "nav.contact": "Contact Us",
    "solutions.infra_digitale": "Digital Infrastructure",
    "solutions.infra_reseau": "Network Infrastructure",
    "solutions.datacenter": "Datacenter",
    "solutions.cybersecurite": "Cybersecurity",
    "solutions.videosurveillance": "Video Surveillance",
    "solutions.controle_acces": "Access Control",
    "solutions.telephonie_ip": "IP Telephony",
    "solutions.salles_reunion": "Meeting Rooms",
    "solutions.sonorisation": "Sound Systems",
    "solutions.managed": "Managed Services",
    "hero.badge": "GTEL Store — Professional Equipment",
    "hero.title.pre": "B2B Technology",
    "hero.title.accent": "Catalogue",
    "hero.desc": "A rigorous selection of the best network equipment, enterprise servers, active security and collaboration solutions. Configured and deployed across Morocco.",
    "hero.metric1.value": "16+",
    "hero.metric1.label": "In-stock references",
    "hero.metric2.value": "4",
    "hero.metric2.label": "Equipment families",
    "hero.metric3.value": "100%",
    "hero.metric3.label": "B2B support in Morocco",
    "filters.all": "All",
    "filters.network": "Network &amp; Security",
    "filters.server": "Servers &amp; Storage",
    "filters.comms": "Collaboration &amp; VoIP",
    "filters.cctv": "Access Control &amp; CCTV",
    "search.placeholder": "Search by model, brand…",
    "results.count": "{n} items",
    "empty.title": "No equipment found",
    "empty.desc": "Sorry, no equipment matches your search criteria. Try different keywords.",
    "cta.requestPrice": "Request Price",
    "price.label": "B2B Price",
    "ctaband.title": "Have an equipment project to quote? Our IT consultants respond within 24h.",
    "ctaband.button": "Request a study",
    "footer.brandDesc": "Moroccan expert in network solutions, cyber-intelligence and integrated telecommunications infrastructure in Casablanca and across the kingdom.",
    "footer.navTitle": "Navigation",
    "footer.navHome": "Home",
    "footer.navSolutions": "Our Solutions",
    "footer.navCatalogue": "Equipment Catalogue",
    "footer.navAbout": "Our Expertise",
    "footer.officeTitle": "Morocco Office",
    "footer.address": "Corner of Rue Al-Quaid / Bd d'Anfa, Casablanca, Morocco",
    "footer.phone": "+212 (0) 522 45 67 89 / 90",
    "footer.email": "contact@gtel.ma",
    "footer.copy": "© 2025 GTEL. All rights reserved. Built with expertise in Morocco.",
    "footer.legal": "Legal Notice",
    "footer.privacy": "Privacy Policy",
    "modal.title": "B2B Study Request",
    "modal.desc": "Configure your equipment connections with the rigor of certified IT consultants.",
    "modal.titleProduct": "B2B Quote Request",
    "modal.labelName": "Full name / Company *",
    "modal.placeholderName": "E.g: Auto Hall Maroc",
    "modal.labelEmail": "Professional email address *",
    "modal.placeholderEmail": "E.g: purchase@company.com",
    "modal.labelPhone": "Phone number *",
    "modal.placeholderPhone": "E.g: +212 661 234 567",
    "modal.labelProduct": "Equipment of interest",
    "modal.labelQty": "Estimated quantity",
    "modal.submit": "Send my price request",
    "modal.requiredAlert": "Please fill in the required fields (*)",
    "toast.success.title": "Request Sent Successfully!",
    "toast.success.desc": "Our network analysts are preparing your personalized quote.",
    "toast.local.desc": "Request sent (Local/Simulation mode)!",
    "theme.toLight": "Switch to light mode",
    "theme.toDark": "Switch to dark mode",
    "lang.current": "EN"
  }
};