/* ==========================================================================
   GTEL — translit.js
   Petit moteur de traduction FR / AR / EN piloté par attributs data-i18n.
   - data-i18n="clef"              -> remplace le innerHTML de l'élément
   - data-i18n-placeholder="clef"  -> remplace l'attribut placeholder
   - Persiste le choix dans localStorage ("gtel-lang")
   - Bascule le sens de lecture (dir="rtl") automatiquement pour l'arabe
   ========================================================================== */

const I18N = {
  fr: {
    "nav.home": "Accueil",
    "nav.solutions": "Solutions",
    "nav.contact": "Nous Contacter",
    "solutions.network.title": "Infrastructure Réseau",
    "solutions.datacenter.title": "Datacenter",
    "solutions.cyber.title": "Cybersécurité",
    "solutions.video.title": "Vidéosurveillance",
    "solutions.access.title": "Contrôle d'Accès",
    "solutions.telephony.title": "Téléphonie IP",
    "solutions.meeting.title": "Salles de Réunion",
    "solutions.sound.title": "Sonorisation",
    "solutions.managed.title": "Services Managés",
    "solutions.digital.title": "Infrastructure Digitale",
    "hero.badge": "Intégration & Solutions IT",
    "hero.title": "L'infrastructure technique de votre entreprise,",
    "hero.title_highlight": "conçue, déployée et tenue.",
    "hero.description": "Au-delà du catalogue. Gtelstore intervient sur l'ensemble du cycle de vie de votre infrastructure IT — depuis l'audit initial jusqu'à la supervision en exploitation.",
    "hero.cta_audit": "Demander un audit",
    "hero.cta_poles": "Nos Pôles d'expertise",
    "stats.experience": "Ans d'expérience",
    "stats.projects": "Projets livrés",
    "stats.partners": "Marques partenaires",
    "stats.support": "Support disponible",
    "vision.badge": "Notre Vision",
    "vision.title": "La différence d'un",
    "vision.title_2": "véritable intégrateur",
    "vision.text1": "Une infrastructure IT performante ne se résume pas à du bon matériel. Elle exige une architecture pensée pour vos usages, un déploiement maîtrisé et une exploitation tenue dans le temps. C'est précisément ce que Gtelstore opère pour les entreprises marocaines depuis sa création : la convergence d'une plateforme de distribution B2B reconnue et d'une équipe d'intégration capable de prendre en charge vos projets de bout en bout.",
    "vision.text2": "Cette intégration verticale — du conseil au matériel, du déploiement à la maintenance — constitue notre différence. Elle vous garantit la cohérence technique, la maîtrise des délais et la responsabilité unique d'un interlocuteur qui assume l'ensemble du périmètre. Là où d'autres vous renvoient vers leurs partenaires, nous gardons la main sur chaque étape.",
    "principles.p1_title": "Audit avant proposition",
    "principles.p1_desc": "Nous n'envoyons jamais de devis sans avoir compris votre contexte. L'audit n'est pas une étape commerciale : c'est la condition d'une offre pertinente.",
    "principles.p2_title": "Indépendance constructeur",
    "principles.p2_desc": "Notre catalogue multi-marques nous permet de recommander la solution la plus adaptée, et non la plus margée. C'est notre garantie de loyauté.",
    "principles.p3_title": "Continuité matérielle",
    "principles.p3_desc": "La plateforme gtelstore.ma assure la disponibilité du matériel spécifié, le réapprovisionnement et le remplacement sous garantie.",
    "principles.p4_title": "Engagement post-déploiement",
    "principles.p4_desc": "Notre relation ne s'arrête pas à la livraison. Nos contrats de supervision assurent la performance de votre infrastructure dans la durée, avec SLA.",
    "filter.all": "Tous nos services",
    "filter.networks": "Télécom & Réseau",
    "filter.security": "Sécurité & Contrôle",
    "filter.facilities": "Infras & Multimédia",
    "filter.search": "RECHERCHER UNE SOLUTION...",
    "solutions.network.desc": "Conception, câblage structuré et configurations de switchs/routeurs haut débit stables.",
    "solutions.network.more": "En savoir plus",
    "solutions.datacenter.desc": "Urbanisation, serveurs, stockage distribué, alimentation sécurisée et refroidissement optimisé.",
    "solutions.datacenter.more": "En savoir plus",
    "solutions.cyber.desc": "Firewall UTM, audits de vulnérabilité, protection endpoint, conformité réglementaire (DNRT).",
    "solutions.cyber.more": "En savoir plus",
    "solutions.video.desc": "Systèmes IP UHD intelligentes, caméras thermiques, stockage d'enregistrement et monitoring IA.",
    "solutions.video.more": "En savoir plus",
    "solutions.access.desc": "Lecteurs RFID, biométrie avancée, barrières d'accès, portillons et gestion centralisée horaire.",
    "solutions.access.more": "En savoir plus",
    "solutions.telephony.desc": "Solutions IPBX, téléphones VoIP polycom/Cisco, communications unifiées de pointe.",
    "solutions.telephony.more": "En savoir plus",
    "solutions.meeting.desc": "Vidéoconférence UHD, écrans interactifs tactiles, micros omnidirectionnels et domotique de salle.",
    "solutions.meeting.more": "En savoir plus",
    "solutions.sound.desc": "Systèmes audio professionnels pour locaux commerciaux, halls de réception et usines.",
    "solutions.sound.more": "En savoir plus",
    "solutions.managed.desc": "Supervision 24/7 de votre parc IT, assistance technique (MCO), haute disponibilité et SLA garantis.",
    "solutions.managed.more": "En savoir plus",
    "solutions.digital.desc": "Audit, conception, modélisation cloud hybride, haute disponibilité et résilience d'écosystèmes IT.",
    "solutions.digital.more": "En savoir plus",
    "poles.badge": "Vision Détaillée",
    "poles.title": "Nos 4 pôles d'expertise",
    "poles.subtitle": "Découvrez comment nos expertises s'imbriquent pour former un socle technologique solide.",
    "poles.p1_title": "Pôle 01 — Infrastructure & Réseaux",
    "poles.p1_desc": "Les fondations techniques qui rendent votre entreprise opérationnelle.",
    "poles.p1_i1": "<strong>Infrastructure Réseau</strong> — LAN, Wi-Fi haute densité, WAN inter-sites, câblage cuivre et fibre optique.",
    "poles.p1_i2": "<strong>Datacenter & Salle Serveur</strong> — Conception, équipements actifs, climatisation, ondulage, supervision.",
    "poles.p1_i3": "<strong>Solutions d'Impression</strong> — Parc d'impression centralisé, gestion des consommables, suivi des coûts.",
    "poles.p2_title": "Pôle 02 — Sécurité & Sûreté",
    "poles.p2_desc": "La protection unifiée de vos actifs numériques et physiques.",
    "poles.p2_i1": "<strong>Cybersécurité</strong> — Pare-feu de nouvelle génération, segmentation réseau, EDR, sauvegarde, conformité.",
    "poles.p2_i2": "<strong>Vidéosurveillance & Vision</strong> — Caméras IP, analyse comportementale par IA, détection d'événements.",
    "poles.p2_i3": "<strong>Contrôle d'Accès</strong> — Badges RFID, biométrie, anti-intrusion, intégration avec la vidéosurveillance.",
    "poles.p3_title": "Pôle 03 — Communication",
    "poles.p3_desc": "Les outils qui font circuler l'information dans votre organisation.",
    "poles.p3_i1": "<strong>Téléphonie IP & UC</strong> — Systèmes IPBX, softphones, intégration CRM, solutions de mobilité.",
    "poles.p3_i2": "<strong>Salles de Réunion</strong> — Intégration audio-vidéo, salles « one-touch », compatibilité Teams/Zoom/Meet.",
    "poles.p3_i3": "<strong>Sonorisation & Acoustique</strong> — Sonorisation multi-zones, sound masking, traitement acoustique.",
    "poles.p4_title": "Pôle 04 — Services Managés",
    "poles.p4_desc": "L'exploitation maîtrisée dans la durée.",
    "poles.p4_i1": "Audit, maintenance préventive et corrective, supervision proactive, gestion des incidents, accompagnement à l'évolution. Service transverse à tous les pôles de l'entreprise.",
    "sectors.title": "Ils nous font confiance",
    "sectors.subtitle": "Expertise Sectorielle",
    "sectors.desc": "Des solutions éprouvées et adaptées aux contraintes de chaque grand secteur d'activité au Maroc.",
    "sectors.industry": "Industrie & Production",
    "sectors.retail": "Retail & Hôtellerie",
    "sectors.health": "Santé & Cliniques",
    "sectors.tertiary": "Tertiaire & Sièges",
    "sectors.education": "Enseignement",
    "partners.title": "Écosystème",
    "partners.subtitle": "Nos partenaires technologiques",
    "partners.desc": "Nous nous appuyons sur les leaders mondiaux pour garantir la pérennité et la performance de vos infrastructures.",
    "partners.cat1": "Réseau & Wi-Fi",
    "partners.cat2": "Sécurité & Vidéosurveillance",
    "partners.cat3": "Communication & Collaboration",
    "partners.cat4": "Datacenter & Énergie",
    "partners.cat5": "Audio & Vidéo professionnel",
    "cta.title": "Prenez rendez-vous avec un de nos ingénieurs",
    "cta.desc": "Un échange de 30 minutes, sans engagement, pour comprendre votre contexte et cibler les priorités.",
    "cta.button": "Parlons de votre projet",
    "footer.desc": "Expert marocain en solutions réseaux, cyber-intelligence et infrastructures de télécommunications intégrées à Casablanca et sur tout le royaume.",
    "footer.nav": "Navigation",
    "footer.home": "Accueil",
    "footer.solutions": "Nos Solutions",
    "footer.expertise": "Notre Expertise",
    "footer.diagnostic": "Demander un diagnostic",
    "footer.contact": "Informations de contact",
    "footer.languages": "Langues",
    "footer.copyright": "&copy; 2025 GTEL. Tous droits réservés. Intégré avec expertise au Maroc.",
    "footer.legal": "Mentions Légales",
    "footer.privacy": "Politique de Confidentialité",
    "modal.badge": "Demande d'étude & contact",
    "modal.title": "Demande de Devis",
    "modal.desc": "Définissez et configurez vos infrastructures ou audits informatiques avec l'ingénierie intégrée GTEL Maroc.",
    "modal.name": "Nom complet / Entreprise *",
    "modal.phone": "Téléphone *",
    "modal.email": "Email professionnel *",
    "modal.service": "Solution ciblée",
    "modal.message": "Détails de votre besoin",
    "modal.submit": "Transmettre la demande d'étude",
    "toast.success": "Demande Envoyée !",
    "toast.desc": "Nos consultants IT préparent votre dossier."
  },

  en: {
    "nav.home": "Home",
    "nav.solutions": "Solutions",
    "nav.contact": "Contact Us",
    "solutions.network.title": "Network Infrastructure",
    "solutions.datacenter.title": "Datacenter",
    "solutions.cyber.title": "Cybersecurity",
    "solutions.video.title": "Video Surveillance",
    "solutions.access.title": "Access Control",
    "solutions.telephony.title": "IP Telephony",
    "solutions.meeting.title": "Meeting Rooms",
    "solutions.sound.title": "Sound Systems",
    "solutions.managed.title": "Managed Services",
    "solutions.digital.title": "Digital Infrastructure",
    "hero.badge": "IT Integration & Solutions",
    "hero.title": "Your company's technical infrastructure,",
    "hero.title_highlight": "designed, deployed and maintained.",
    "hero.description": "Beyond the catalogue. Gtelstore covers the full lifecycle of your IT infrastructure — from initial audit to ongoing supervision.",
    "hero.cta_audit": "Request an audit",
    "hero.cta_poles": "Our areas of expertise",
    "stats.experience": "Years of experience",
    "stats.projects": "Projects delivered",
    "stats.partners": "Partner brands",
    "stats.support": "Support available",
    "vision.badge": "Our Vision",
    "vision.title": "The difference of a",
    "vision.title_2": "genuine integrator",
    "vision.text1": "High-performing IT infrastructure isn't just about good hardware. It requires an architecture designed around how you work, a controlled rollout and operations sustained over time. That is exactly what Gtelstore has done for Moroccan companies since its founding: bringing together a recognised B2B distribution platform and an integration team able to run your projects end to end.",
    "vision.text2": "This vertical integration — from consulting to hardware, from deployment to maintenance — is what sets us apart. It guarantees technical consistency, control over timelines and a single point of accountability for the whole scope. Where others hand you off to their partners, we keep control of every step.",
    "principles.p1_title": "Audit before proposal",
    "principles.p1_desc": "We never send a quote without first understanding your context. The audit isn't a sales step — it's the condition for a relevant offer.",
    "principles.p2_title": "Vendor independence",
    "principles.p2_desc": "Our multi-brand catalogue lets us recommend the solution best suited to you, not the most profitable one for us. That's our guarantee of loyalty.",
    "principles.p3_title": "Hardware continuity",
    "principles.p3_desc": "The gtelstore.ma platform ensures availability of the specified hardware, restocking and warranty replacement.",
    "principles.p4_title": "Post-deployment commitment",
    "principles.p4_desc": "Our relationship doesn't end at delivery. Our supervision contracts keep your infrastructure performing over the long run, with SLAs.",
    "filter.all": "All services",
    "filter.networks": "Telecom & Network",
    "filter.security": "Security & Access",
    "filter.facilities": "Facilities & Multimedia",
    "filter.search": "SEARCH A SOLUTION...",
    "solutions.network.desc": "Design, structured cabling and configuration of stable high-throughput switches and routers.",
    "solutions.network.more": "Learn more",
    "solutions.datacenter.desc": "Layout, servers, distributed storage, secure power supply and optimised cooling.",
    "solutions.datacenter.more": "Learn more",
    "solutions.cyber.desc": "UTM firewalls, vulnerability audits, endpoint protection, regulatory compliance (DNRT).",
    "solutions.cyber.more": "Learn more",
    "solutions.video.desc": "Smart UHD IP systems, thermal cameras, recording storage and AI-powered monitoring.",
    "solutions.video.more": "Learn more",
    "solutions.access.desc": "RFID readers, advanced biometrics, access barriers, turnstiles and centralised time management.",
    "solutions.access.more": "Learn more",
    "solutions.telephony.desc": "IPBX solutions, Polycom/Cisco VoIP handsets, state-of-the-art unified communications.",
    "solutions.telephony.more": "Learn more",
    "solutions.meeting.desc": "UHD video conferencing, interactive touch screens, omnidirectional microphones and room automation.",
    "solutions.meeting.more": "Learn more",
    "solutions.sound.desc": "Professional audio systems for retail spaces, reception halls and factories.",
    "solutions.sound.more": "Learn more",
    "solutions.managed.desc": "24/7 supervision of your IT estate, technical support (MCO), high availability and guaranteed SLAs.",
    "solutions.managed.more": "Learn more",
    "solutions.digital.desc": "Audit, design and hybrid-cloud modelling for highly available, resilient IT ecosystems.",
    "solutions.digital.more": "Learn more",
    "poles.badge": "Detailed Overview",
    "poles.title": "Our 4 areas of expertise",
    "poles.subtitle": "See how our areas of expertise interlock to form a solid technology foundation.",
    "poles.p1_title": "Area 01 — Infrastructure & Networks",
    "poles.p1_desc": "The technical foundations that keep your business running.",
    "poles.p1_i1": "<strong>Network Infrastructure</strong> — LAN, high-density Wi-Fi, site-to-site WAN, copper and fibre cabling.",
    "poles.p1_i2": "<strong>Datacenter & Server Room</strong> — Design, active equipment, cooling, UPS, supervision.",
    "poles.p1_i3": "<strong>Print Solutions</strong> — Centralised print fleet, consumables management, cost tracking.",
    "poles.p2_title": "Area 02 — Security & Safety",
    "poles.p2_desc": "Unified protection for your digital and physical assets.",
    "poles.p2_i1": "<strong>Cybersecurity</strong> — Next-gen firewalls, network segmentation, EDR, backup, compliance.",
    "poles.p2_i2": "<strong>Video Surveillance & Vision</strong> — IP cameras, AI-based behavioural analysis, event detection.",
    "poles.p2_i3": "<strong>Access Control</strong> — RFID badges, biometrics, intrusion detection, integrated with video surveillance.",
    "poles.p3_title": "Area 03 — Communication",
    "poles.p3_desc": "The tools that keep information flowing across your organisation.",
    "poles.p3_i1": "<strong>IP Telephony & UC</strong> — IPBX systems, softphones, CRM integration, mobility solutions.",
    "poles.p3_i2": "<strong>Meeting Rooms</strong> — Audio-video integration, one-touch rooms, Teams/Zoom/Meet compatibility.",
    "poles.p3_i3": "<strong>Sound & Acoustics</strong> — Multi-zone sound systems, sound masking, acoustic treatment.",
    "poles.p4_title": "Area 04 — Managed Services",
    "poles.p4_desc": "Operations kept under control over the long run.",
    "poles.p4_i1": "Audit, preventive and corrective maintenance, proactive supervision, incident management, support through change. A service that runs across every area of the business.",
    "sectors.title": "Trusted by",
    "sectors.subtitle": "Sector Expertise",
    "sectors.desc": "Proven solutions adapted to the constraints of each major industry in Morocco.",
    "sectors.industry": "Industry & Manufacturing",
    "sectors.retail": "Retail & Hospitality",
    "sectors.health": "Healthcare & Clinics",
    "sectors.tertiary": "Corporate & HQs",
    "sectors.education": "Education",
    "partners.title": "Ecosystem",
    "partners.subtitle": "Our technology partners",
    "partners.desc": "We rely on world leaders to guarantee the longevity and performance of your infrastructure.",
    "partners.cat1": "Network & Wi-Fi",
    "partners.cat2": "Security & Video Surveillance",
    "partners.cat3": "Communication & Collaboration",
    "partners.cat4": "Datacenter & Power",
    "partners.cat5": "Professional Audio & Video",
    "cta.title": "Book a call with one of our engineers",
    "cta.desc": "A free, no-commitment 30-minute conversation to understand your context and identify priorities.",
    "cta.button": "Let's talk about your project",
    "footer.desc": "Moroccan expert in network solutions, cyber-intelligence and integrated telecom infrastructure across Casablanca and the whole kingdom.",
    "footer.nav": "Navigation",
    "footer.home": "Home",
    "footer.solutions": "Our Solutions",
    "footer.expertise": "Our Expertise",
    "footer.diagnostic": "Request a diagnostic",
    "footer.contact": "Contact information",
    "footer.languages": "Languages",
    "footer.copyright": "&copy; 2025 GTEL. All rights reserved. Integrated with expertise in Morocco.",
    "footer.legal": "Legal Notice",
    "footer.privacy": "Privacy Policy",
    "modal.badge": "Request & contact",
    "modal.title": "Request a Quote",
    "modal.desc": "Define and configure your IT infrastructure or audits with GTEL Morocco's integrated engineering team.",
    "modal.name": "Full name / Company *",
    "modal.phone": "Phone *",
    "modal.email": "Business email *",
    "modal.service": "Targeted solution",
    "modal.message": "Details of your needs",
    "modal.submit": "Send request",
    "toast.success": "Request Sent!",
    "toast.desc": "Our IT consultants are preparing your file."
  },

  ar: {
    "nav.home": "الرئيسية",
    "nav.solutions": "الحلول",
    "nav.contact": "اتصل بنا",
    "solutions.network.title": "البنية التحتية للشبكات",
    "solutions.datacenter.title": "مركز البيانات",
    "solutions.cyber.title": "الأمن السيبراني",
    "solutions.video.title": "المراقبة بالفيديو",
    "solutions.access.title": "التحكم في الولوج",
    "solutions.telephony.title": "الهاتف عبر الإنترنت",
    "solutions.meeting.title": "قاعات الاجتماعات",
    "solutions.sound.title": "أنظمة الصوت",
    "solutions.managed.title": "الخدمات المُدارة",
    "solutions.digital.title": "البنية التحتية الرقمية",
    "hero.badge": "تكامل وحلول تقنية المعلومات",
    "hero.title": "البنية التقنية لمؤسستكم،",
    "hero.title_highlight": "مُصمَّمة، مُنجزة ومُتابَعة.",
    "hero.description": "أبعد من مجرد كتالوج. تتدخل Gtelstore في كامل دورة حياة بنيتكم التحتية المعلوماتية — من التشخيص الأولي إلى الإشراف أثناء الاستغلال.",
    "hero.cta_audit": "طلب تشخيص",
    "hero.cta_poles": "مجالات خبرتنا",
    "stats.experience": "سنوات من الخبرة",
    "stats.projects": "مشروع منجَز",
    "stats.partners": "علامة شريكة",
    "stats.support": "دعم متواصل",
    "vision.badge": "رؤيتنا",
    "vision.title": "الفرق الذي يصنعه",
    "vision.title_2": "مُدمِج حقيقي",
    "vision.text1": "لا تقتصر البنية التحتية المعلوماتية الفعّالة على جودة المعدات فقط. إنها تتطلب هندسة مصمَّمة وفق استخداماتكم، ونشرًا مُتحكَّمًا فيه، واستغلالًا مستمرًا عبر الزمن. هذا بالضبط ما تقدمه Gtelstore للشركات المغربية منذ تأسيسها: التقاء منصة توزيع B2B معترف بها مع فريق تكامل قادر على تولي مشاريعكم من الألف إلى الياء.",
    "vision.text2": "هذا التكامل العمودي — من الاستشارة إلى المعدات، ومن النشر إلى الصيانة — هو ما يميزنا. فهو يضمن لكم الانسجام التقني، والتحكم في الآجال، ومسؤولية موحّدة لدى محاور واحد يتكفل بكامل النطاق. وحيث يحيلكم آخرون على شركائهم، نبقى نحن ممسكين بزمام كل مرحلة.",
    "principles.p1_title": "تشخيص قبل العرض",
    "principles.p1_desc": "لا نرسل أبدًا عرض ثمن دون فهم سياقكم. التشخيص ليس خطوة تجارية، بل شرط لتقديم عرض ملائم.",
    "principles.p2_title": "استقلالية عن الموردين",
    "principles.p2_desc": "يتيح لنا كتالوجنا متعدد العلامات التوصية بالحل الأنسب، وليس الأكثر ربحية. هذا ضمان لولائنا.",
    "principles.p3_title": "استمرارية المعدات",
    "principles.p3_desc": "تضمن منصة gtelstore.ma توفر المعدات المحددة، وإعادة التزويد، والاستبدال في إطار الضمان.",
    "principles.p4_title": "التزام ما بعد النشر",
    "principles.p4_desc": "علاقتنا لا تنتهي عند التسليم. تضمن عقود الإشراف لدينا أداء بنيتكم التحتية على المدى الطويل، بموجب اتفاقيات مستوى الخدمة.",
    "filter.all": "جميع خدماتنا",
    "filter.networks": "الاتصالات والشبكات",
    "filter.security": "الأمن والتحكم",
    "filter.facilities": "البنى التحتية والوسائط",
    "filter.search": "ابحث عن حل...",
    "solutions.network.desc": "تصميم، وكابلات منظَّمة، وضبط لمبدّلات وموجّهات عالية السرعة ومستقرة.",
    "solutions.network.more": "المزيد",
    "solutions.datacenter.desc": "تهيئة، خوادم، تخزين موزَّع، تغذية كهربائية آمنة وتبريد مُحسَّن.",
    "solutions.datacenter.more": "المزيد",
    "solutions.cyber.desc": "جدران حماية UTM، تدقيق للثغرات، حماية نقاط النهاية، امتثال تنظيمي (DNRT).",
    "solutions.cyber.more": "المزيد",
    "solutions.video.desc": "أنظمة IP ذكية بدقة UHD، كاميرات حرارية، تخزين للتسجيلات ومراقبة بالذكاء الاصطناعي.",
    "solutions.video.more": "المزيد",
    "solutions.access.desc": "قارئات RFID، قياسات حيوية متقدمة، حواجز ولوج، بوابات دوّارة وتسيير مركزي للتوقيت.",
    "solutions.access.more": "المزيد",
    "solutions.telephony.desc": "حلول IPBX، هواتف VoIP من Polycom/Cisco، اتصالات موحّدة متطورة.",
    "solutions.telephony.more": "المزيد",
    "solutions.meeting.desc": "تحاور بالفيديو بدقة UHD، شاشات تفاعلية باللمس، ميكروفونات محيطية وأتمتة القاعة.",
    "solutions.meeting.more": "المزيد",
    "solutions.sound.desc": "أنظمة صوتية احترافية للمحلات التجارية وقاعات الاستقبال والمصانع.",
    "solutions.sound.more": "المزيد",
    "solutions.managed.desc": "إشراف على مدار الساعة على أسطولكم المعلوماتي، دعم تقني، توفر عالٍ واتفاقيات مستوى خدمة مضمونة.",
    "solutions.managed.more": "المزيد",
    "solutions.digital.desc": "تشخيص، تصميم ونمذجة سحابية هجينة، من أجل بنية معلوماتية عالية التوفر ومرنة.",
    "solutions.digital.more": "المزيد",
    "poles.badge": "رؤية تفصيلية",
    "poles.title": "أربعة مجالات لخبرتنا",
    "poles.subtitle": "اكتشفوا كيف تتكامل خبراتنا لتشكيل قاعدة تقنية متينة.",
    "poles.p1_title": "المجال 01 — البنية التحتية والشبكات",
    "poles.p1_desc": "الأسس التقنية التي تجعل مؤسستكم قادرة على العمل.",
    "poles.p1_i1": "<strong>البنية التحتية للشبكات</strong> — شبكة محلية، واي فاي عالي الكثافة، شبكة واسعة بين المواقع، أسلاك نحاسية وألياف بصرية.",
    "poles.p1_i2": "<strong>مركز البيانات وقاعة الخوادم</strong> — تصميم، معدات فعّالة، تكييف، مزود طاقة احتياطي، إشراف.",
    "poles.p1_i3": "<strong>حلول الطباعة</strong> — أسطول طباعة مركزي، تسيير المواد المستهلكة، متابعة التكاليف.",
    "poles.p2_title": "المجال 02 — الأمن والسلامة",
    "poles.p2_desc": "حماية موحّدة لأصولكم الرقمية والمادية.",
    "poles.p2_i1": "<strong>الأمن السيبراني</strong> — جدران حماية من الجيل الجديد، تقسيم الشبكة، كشف واستجابة لنقاط النهاية، نسخ احتياطي، امتثال.",
    "poles.p2_i2": "<strong>المراقبة بالفيديو والرؤية</strong> — كاميرات IP، تحليل سلوكي بالذكاء الاصطناعي، كشف الأحداث.",
    "poles.p2_i3": "<strong>التحكم في الولوج</strong> — شارات RFID، قياسات حيوية، كشف التسلل، تكامل مع المراقبة بالفيديو.",
    "poles.p3_title": "المجال 03 — الاتصال",
    "poles.p3_desc": "الأدوات التي تُنشئ تدفق المعلومة داخل مؤسستكم.",
    "poles.p3_i1": "<strong>الهاتف عبر الإنترنت والاتصالات الموحّدة</strong> — أنظمة IPBX، هواتف برمجية، تكامل مع CRM، حلول التنقل.",
    "poles.p3_i2": "<strong>قاعات الاجتماعات</strong> — تكامل صوتي ومرئي، قاعات بلمسة واحدة، توافق مع Teams/Zoom/Meet.",
    "poles.p3_i3": "<strong>الصوت والصوتيات</strong> — أنظمة صوتية متعددة المناطق، تمويه صوتي، معالجة صوتية.",
    "poles.p4_title": "المجال 04 — الخدمات المُدارة",
    "poles.p4_desc": "استغلال محكوم على المدى الطويل.",
    "poles.p4_i1": "تشخيص، صيانة وقائية وتصحيحية، إشراف استباقي، تسيير الحوادث، مواكبة التطور. خدمة أفقية تشمل جميع مجالات المؤسسة.",
    "sectors.title": "يثقون بنا",
    "sectors.subtitle": "خبرة قطاعية",
    "sectors.desc": "حلول مُجرَّبة ومُكيَّفة مع خصوصيات كل قطاع نشاط رئيسي بالمغرب.",
    "sectors.industry": "الصناعة والإنتاج",
    "sectors.retail": "التجزئة والفندقة",
    "sectors.health": "الصحة والعيادات",
    "sectors.tertiary": "القطاع الثالث والمقرات",
    "sectors.education": "التعليم",
    "partners.title": "المنظومة",
    "partners.subtitle": "شركاؤنا التقنيون",
    "partners.desc": "نعتمد على الرواد العالميين لضمان استدامة وأداء بنيتكم التحتية.",
    "partners.cat1": "الشبكات والواي فاي",
    "partners.cat2": "الأمن والمراقبة بالفيديو",
    "partners.cat3": "الاتصال والتعاون",
    "partners.cat4": "مركز البيانات والطاقة",
    "partners.cat5": "الصوت والفيديو الاحترافي",
    "cta.title": "احجزوا موعدًا مع أحد مهندسينا",
    "cta.desc": "نقاش مجاني لمدة 30 دقيقة، دون أي التزام، لفهم سياقكم وتحديد الأولويات.",
    "cta.button": "لنتحدث عن مشروعكم",
    "footer.desc": "خبير مغربي في حلول الشبكات، والاستخبار السيبراني، والبنى التحتية للاتصالات المُدمجة بالدار البيضاء وعبر المملكة.",
    "footer.nav": "التصفح",
    "footer.home": "الرئيسية",
    "footer.solutions": "حلولنا",
    "footer.expertise": "خبرتنا",
    "footer.diagnostic": "طلب تشخيص",
    "footer.contact": "معلومات الاتصال",
    "footer.languages": "اللغات",
    "footer.copyright": "© 2025 GTEL. جميع الحقوق محفوظة. بخبرة مُدمجة في المغرب.",
    "footer.legal": "الإشعار القانوني",
    "footer.privacy": "سياسة الخصوصية",
    "modal.badge": "طلب دراسة واتصال",
    "modal.title": "طلب عرض ثمن",
    "modal.desc": "حدّدوا واضبطوا بنيتكم التحتية أو تدقيقاتكم المعلوماتية مع فريق هندسة GTEL المغرب المُدمج.",
    "modal.name": "الاسم الكامل / المؤسسة *",
    "modal.phone": "الهاتف *",
    "modal.email": "البريد الإلكتروني المهني *",
    "modal.service": "الحل المستهدف",
    "modal.message": "تفاصيل احتياجكم",
    "modal.submit": "إرسال طلب الدراسة",
    "toast.success": "تم إرسال الطلب!",
    "toast.desc": "يقوم مستشارونا التقنيون بإعداد ملفكم."
  }
};

const translit = {
  current: 'fr',

  init(lang) {
    const saved = localStorage.getItem('gtel-lang');
    this.change(saved || lang || 'fr', true);
  },

  change(lang, silent) {
    if (!I18N[lang]) return;
    this.current = lang;
    localStorage.setItem('gtel-lang', lang);

    document.documentElement.setAttribute('lang', lang);
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');

    const dict = I18N[lang];

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (dict[key] !== undefined) el.innerHTML = dict[key];
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      if (dict[key] !== undefined) el.setAttribute('placeholder', dict[key]);
    });

    const flags = { fr: '🇫🇷', ar: '🇲🇦', en: '🇬🇧' };
    document.querySelectorAll('[data-translit-flag]').forEach(el => el.textContent = flags[lang]);
    document.querySelectorAll('[data-translit-code]').forEach(el => el.textContent = lang.toUpperCase());
    document.querySelectorAll('[data-translit-active]').forEach(el => {
      el.classList.toggle('active', el.getAttribute('data-translit-active') === lang);
    });

    if (!silent) {
      window.dispatchEvent(new CustomEvent('gtel:langchange', { detail: { lang } }));
    }
  }
};